<?php
session_start();
require_once('../../config/db.php');
require_once('../../includes/tcpdf/tcpdf.php'); 
 
if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'Administrator') {
    die("Access Denied. You do not have permission to generate this report.");
}
 
$start = isset($_GET['start']) ? $_GET['start'] : date('Y-m-01');
$end = isset($_GET['end']) ? $_GET['end'] : date('Y-m-t');
 
$sql = "SELECT p.*, i.id as inv_id, r.deceased_name, u.full_name as staff 
        FROM payments p 
        JOIN invoices i ON p.invoice_id = i.id 
        JOIN reservations r ON i.reservation_id = r.id
        LEFT JOIN users u ON p.received_by = u.id
        WHERE DATE(p.payment_date) BETWEEN ? AND ? 
        ORDER BY p.payment_date ASC";

$stmt = mysqli_prepare($conn, $sql);
mysqli_stmt_bind_param($stmt, "ss", $start, $end);
mysqli_stmt_execute($stmt);
$result = mysqli_stmt_get_result($stmt);

$total_sales = 0;
$total_transactions = mysqli_num_rows($result);
 
class MYPDF extends TCPDF { 
    public function Footer() {
        $this->SetY(-15); 
        $this->SetFont('dejavusans', 'I', 8);
        $this->SetTextColor(119, 141, 169);  
        $this->Cell(0, 10, 'Memoria: Mortuary Operations & Inventory Management System  |  Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }
}

$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
 
$pdf->SetCreator('Memoria System');
$pdf->SetAuthor('Administrator');
$pdf->SetTitle('Financial Sales Report');
 
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(true);

$pdf->SetMargins(15, 15, 15);
$pdf->SetAutoPageBreak(TRUE, 20);
 
$pdf->SetFont('dejavusans', '', 10);
$pdf->AddPage();
 
$logo_path = '../../assets/img/logo.png';
$logo_img = file_exists($logo_path) ? '<img src="'.$logo_path.'" width="40" height="40" />' : '';
 
$html = '
<style>
    h1 { color: #1B263B; font-size: 22pt; margin-bottom: 0; }
    h2 { color: #415A77; font-size: 14pt; margin-top: 5px; }
    p { color: #778DA9; font-size: 10pt; }
    .header-table { width: 100%; border-bottom: 3px solid #1B263B; padding-bottom: 10px; margin-bottom: 20px; }
    .summary-box { background-color: #E0E1DD; padding: 10px; border-radius: 5px; }
    .data-table { width: 100%; border-collapse: collapse; padding: 8px; }
    .data-table th { background-color: #415A77; color: #FFFFFF; font-weight: bold; text-align: left; }
    .data-table th.right { text-align: right; }
    .data-table td { border-bottom: 1px solid #E0E1DD; color: #333333; }
    .data-table td.right { text-align: right; }
    .total-row td { background-color: #1B263B; color: #FFFFFF; font-weight: bold; font-size: 12pt; border: none; }
</style>

<table class="header-table">
    <tr>
        <td width="10%">' . $logo_img . '</td>
        <td width="90%">
            <h1>MEMORIA</h1>
            <h2>Financial Sales & Collection Report</h2>
        </td>
    </tr>
</table>

<table>
    <tr>
        <td width="50%">
            <p><strong>Date Generated:</strong> ' . date('F d, Y - h:i A') . '<br>
            <strong>Generated By:</strong> ' . htmlspecialchars($_SESSION['full_name']) . '</p>
        </td>
        <td width="50%" align="right">
            <div class="summary-box">
                <p style="color:#1B263B; font-weight:bold;">Report Period:<br>
                <span style="color:#415A77; font-size:11pt;">' . date('M d, Y', strtotime($start)) . ' to ' . date('M d, Y', strtotime($end)) . '</span></p>
            </div>
        </td>
    </tr>
</table>

<br><br>

<table class="data-table">
    <thead>
        <tr>
            <th width="15%">Date</th>
            <th width="15%">Invoice #</th>
            <th width="30%">Client / Deceased</th>
            <th width="20%">Received By</th>
            <th width="20%" class="right">Amount (PHP)</th>
        </tr>
    </thead>
    <tbody>';

if ($total_transactions > 0) {
    $fill = false;
    while ($row = mysqli_fetch_assoc($result)) {
        $total_sales += $row['amount']; 
        $bg_color = $fill ? 'background-color:#F8F9FA;' : 'background-color:#FFFFFF;';
        
        $html .= '<tr style="'.$bg_color.'">
                    <td>' . date('Y-m-d', strtotime($row['payment_date'])) . '</td>
                    <td>INV-' . str_pad($row['inv_id'], 5, '0', STR_PAD_LEFT) . '</td>
                    <td>' . htmlspecialchars($row['deceased_name']) . '</td>
                    <td>' . htmlspecialchars($row['staff']) . '</td>
                    <td class="right">&#8369;' . number_format($row['amount'], 2) . '</td>
                  </tr>';
        $fill = !$fill;  
    }
     
    $html .= '<tr class="total-row">
                <td colspan="4" align="right">GRAND TOTAL COLLECTIONS:</td>
                <td class="right">&#8369;' . number_format($total_sales, 2) . '</td>
              </tr>';
} else {
    $html .= '<tr><td colspan="5" align="center" style="color:#778DA9;"><br><br>No financial transactions recorded for this period.<br><br></td></tr>';
}

$html .= '</tbody></table>
<br><br>
<p style="text-align:center; color:#778DA9; font-size:9pt;">*** END OF REPORT ***<br>This is a system-generated document and does not require a physical signature.</p>';
 
$pdf->writeHTML($html, true, false, true, false, '');
 
$pdf->Output('Memoria_Sales_Report_' . date('Ymd') . '.pdf', 'I');
?>